# Generated by Django 4.1 on 2025-08-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membro',
            old_name='genero',
            new_name='senha',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='membro',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
